name: Check Listings

on:
  schedule:
    - cron: '0 * * * *'    # every hour on the hour
  workflow_dispatch:      # allows manual trigger

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Chromium prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libxshmfence1 \
            libgtk-3-0

      - name: Run scraper bot
        run: node index.js